### ISSUE TITLE
插入耳机再拔出，会出现没声音

### ISSUE THREAD

**Issue by Pmc8090** [hjmmc/Honor-Magicbook#13]
10.15最新的系统，用了大佬最新的EFI包，开始扬声器播放播客的时候，声音正常，插入耳机听了1分钟再拔出，一段时间后会出现没声音了，其实此时播客还是在正常播放着的，麻烦看看，谢谢

**Comment by hjmmc** [comment]
可以试试我编译的AppleALC，声卡ID为57
https://github.com/hjmmc/Honor-Magicbook/issues/4#issuecomment-541416733

**Comment by hjmmc** [comment]
我试过你的操作，没出现声音消失的情况，现在的声卡驱动还是不完美的，估计跟AppleALC核心代码有关，暂时没能力修复

这里还有声卡ID为21的驱动，你也可以试试。[AppleALC.21.fix.kext.zip](https://github.com/hjmmc/Honor-Magicbook/files/3732687/AppleALC.21.fix.kext.zip)
