### ISSUE TITLE
【已解决】使用DW1820A，睡眠后无法唤醒wifi 相关问题

### ISSUE THREAD

**Issue by Jovines** [hjmmc/Honor-Magicbook#19]
我换了网卡  是那块小兵推荐的dw1820a，直接插上就可以驱动，应该是您已经调好了，但是有一个问题是每次休眠之后wifi就不可以用了，不可以打开的那种，之前试着按照小兵的那个教程配置了一遍，但是没有任何效果，还是会有同样的问题，最后还是完全换回您的了，请问有解决办法吗

**Comment by hjmmc** [comment]
把驱动放到/S/L/E下后重建缓存试试

**Comment by JonTree** [comment]
我使用kext utility重建缓存之后还是不行

**Comment by JonTree** [comment]
就是只要一关子盖就会出现这个问题，但是如果是不关子盖，它休眠就会没问题，但是只要一关上子盖，还是会打不开wifi

**Comment by richard-sdr** [comment]
我也有同样的问题，各种换方法驱动都不行，现在是正面2脚短接，休眠的话短时间（5-10分钟）没问题，长时间唤醒就打不开了，log提示如下：
localhost kernel[0]: (AirPortBrcmNIC) <AirPortBrcmNIC`osl_iolog_withtimestamp> ARPT: 704.535465: wl0: _wlc_ioctl: dead chip, off[0] bar0[0xffffffff]

**Comment by richard-sdr** [comment]
今天用小兵blog的驱动方式页面底下评论的方法添加device properties添加pci-aspm-default = 0 再加去掉所有屏蔽之后貌似好了，刚才合盖休眠了十多分钟没啥问题，我再测试一下看看是不是确实好了再回来

**Comment by JonTree** [comment]
> 今天用小兵blog的驱动方式页面底下评论的方法在device properties添加pci-aspm-default = 0 再加去掉所有屏蔽之后貌似好了，刚才合盖休眠了十多分钟没啥问题，我再测试一下看看是不是确实好了再回来
> 
> 合盖30分后重新开机无线正常。问题解决

请问是dw1820那个页面吗，现在呢确认OK了吗

**Comment by JonTree** [comment]
我也加了这个，然后去掉所有的针脚屏蔽之后wifi就打不开了

**Comment by richard-sdr** [comment]
> 我也加了这个，然后去掉所有的针脚屏蔽之后wifi就打不开了，但是蓝牙正常，重建缓存之后wifi都蓝牙无法打开，而且一直无法进设置，鼠标一直在转,然后我把针脚重新按照小兵教程里面的屏蔽之后能用，但是没解决这个问题

我是勾了fix airport，然后去掉boot args里网卡相关参数和原device prop里网卡部分所有数据，只添加aspm，如果这样还不行的话那可能是批次问题？我的是换标的不知道哪个版本，写的是0VW3T3

**Comment by JonTree** [comment]
可以把你的config文件发我一下 jonstree@outlook.com

**Comment by JonTree** [comment]
我也解决了，这里我说一下我解决的步骤，应该跟上面的老哥是一样的，只不过为了照顾萌新详细说一下（我就是萌新）：
* 首先去掉在小兵的驱动教程要求添加的所有东西，以及所有针脚屏蔽
* 如果忘了自己的wifi的pci地址，使用hackintool那个工具得到网卡的pci路径
* 然后在Devices->Properties里面添加设备（也就是填写你获取的pci地址），然后添加设备里面的属性
比如我的pci是`PciRoot(0x0)/Pci(0x1d,0x0)/Pci(0x0,0x0)`
 > 然后往这里面添加属性 pci-aspm-default = 0

**Comment by xianyu-ing** [comment]
> 我也解决了，这里我说一下我解决的步骤，应该跟上面的老哥是一样的，只不过为了照顾萌新详细说一下（我就是萌新）：
> 
> * 首先去掉在小兵的驱动教程要求添加的所有东西，以及所有针脚屏蔽
> * 如果忘了自己的wifi的pci地址，使用hackintool那个工具得到网卡的pci路径
> * 然后在Devices->Properties里面添加设备（也就是填写你获取的pci地址），然后添加设备里面的属性
>   比如我的pci是`PciRoot(0x0)/Pci(0x1d,0x0)/Pci(0x0,0x0)`
> 
> > 然后往这里面添加属性 pci-aspm-default = 0

这个 1820a 有 3 个版本耶，你是用你一个的？

**Comment by richard-sdr** [comment]
回楼上，使用DW1820a 0VW3T3和联想 94350都测试通过完美

**Comment by monuo1984** [comment]
谢谢各位，我的也完美了

**Comment by JonTree** [comment]
对了，如果有人出现了跟我一样这样改了之后，蓝牙无法正常连接蓝牙耳机蓝牙键盘甚至手机的直接添加上小兵教程里说的那几个引导参数就好了，这里我搬运一下：
> 如果蓝牙睡眠唤醒后无法工作，请于config.plist中添加引导参数：bpr_probedelay=100 bpr_initialdelay=300 bpr_postresetdelay=300

**Comment by TheMercueyHotel** [comment]
> 对了，如果有人出现了跟我一样这样改了之后，蓝牙无法正常连接蓝牙耳机蓝牙键盘甚至手机的直接添加上小兵教程里说的那几个引导参数就好了，这里我搬运一下：
> 
> > 如果蓝牙睡眠唤醒后无法工作，请于config.plist中添加引导参数：bpr_probedelay=100 bpr_initialde

> 对了，如果有人出现了跟我一样这样改了之后，蓝牙无法正常连接蓝牙耳机蓝牙键盘甚至手机的直接添加上小兵教程里说的那几个引导参数就好了，这里我搬运一下：
> 
> > 如果蓝牙睡眠唤醒后无法工作，请于config.plist中添加引导参数：bpr_probedelay = 100 bpr_initialdelay = 300 bpr_postresetdelay = 300

**Comment by TheMercueyHotel** [comment]
按照这里已经解决了WIFI休眠不工作的问题，现在蓝牙开不了，也没有蓝牙的logo，请问你们有这个情况吗

**Comment by TheMercueyHotel** [comment]
> 对了，如果有人出现了跟我一样这样改了之后，蓝牙无法正常连接蓝牙耳机蓝牙键盘甚至手机的直接添加上小兵教程里说的那几个引导参数就好了，这里我搬运一下：
> 
> > 如果蓝牙睡眠唤醒后无法工作，请于config.plist中添加引导参数：bpr_probedelay=100 bpr_initialdelay=300 bpr_postresetdelay=300
按照这里已经解决了WIFI休眠不工作的问题，现在蓝牙开不了，也没有蓝牙的logo，请问你们有这个情况吗

**Comment by jieteman** [comment]
> 回楼上，使用DW1820a 0VW3T3和联想 94350都测试通过完美

![346AAC50-9327-4A83-864D-FC90DE0C00C0](https://user-images.githubusercontent.com/52092001/76045403-e7178480-5f97-11ea-8a12-3a3bc3cfe3ea.png)
联想94350是这块吗？我准备买了
