### ISSUE TITLE
建议加上IONVMeFamily，部分512g的机型用LITEON的SSD，抹盘就会找不到硬盘

### ISSUE THREAD

**Issue by hyxing** [hjmmc/Honor-Magicbook#2]

**Comment by hjmmc** [comment]
你 fork 一份，新建个 PR

**Comment by dyhd121** [comment]
也遇到了这个问题，怎么破啊？？？硬盘是LITEON CA3-8D512

**Comment by hjmmc** [comment]
> 也遇到了这个问题，怎么破啊？？？硬盘是LITEON CA3-8D512

https://www.ddmf.net/20181219_158.html

尝试下这个，如果可以，我加到 config 上

**Comment by dyhd121** [comment]
> > 也遇到了这个问题，怎么破啊？？？硬盘是LITEON CA3-8D512
> 
> https://www.ddmf.net/20181219_158.html
> 
> 尝试下这个，如果可以，我加到 config 上



> > 也遇到了这个问题，怎么破啊？？？硬盘是LITEON CA3-8D512
> 
> https://www.ddmf.net/20181219_158.html
> 
> 尝试下这个，如果可以，我加到 config 上
新手，实在不知道如何操作，我这链接需要mac下环境操作？？？，我看着2019版的magicbook也是512的SSD估计想黑也会有这个问题，

**Comment by hjmmc** [comment]
> > > 也遇到了这个问题，怎么破啊？？？硬盘是LITEON CA3-8D512
> > 
> > 
> > https://www.ddmf.net/20181219_158.html
> > 尝试下这个，如果可以，我加到 config 上
> 
> > > 也遇到了这个问题，怎么破啊？？？硬盘是LITEON CA3-8D512
> > 
> > 
> > https://www.ddmf.net/20181219_158.html
> > 尝试下这个，如果可以，我加到 config 上
> > 新手，实在不知道如何操作，我这链接需要mac下环境操作？？？，我看着2019版的magicbook也是512的SSD估计想黑也会有这个问题，

试试这个

[config.plist.zip](https://github.com/hjmmc/Honor-Magicbook/files/3440122/config.plist.zip)

**Comment by wanghaorananda** [comment]
好像西部数据的硬盘也有这个问题，每次格式化的时候 efi分区总会丢失。很迷
