### ISSUE TITLE
现在装的10.14,如果现在更新到最新的efi,会有问题不?

### ISSUE THREAD

**Issue by xiyanglove** [hjmmc/Honor-Magicbook#20]
还有就是,如果装了最新的efi,升级10.15的话,是直接升级还是重装10.15呢?求大佬解答一下

**Comment by hjmmc** [comment]
应该没问题的，可以先备份当前的EFI，不行再换回来，我是升级到10.15的

**Comment by xiyanglove** [comment]
好的,谢谢,明天就更新到最新的EFI

**Comment by xiyanglove** [comment]
我更新到最新的EFI了,为什么我关盖子后再打开还是黑屏,还是需要重新开合才能亮屏呢

**Comment by xiyanglove** [comment]
系统还没更新到10.15的
