### ISSUE TITLE
请问大神10.15.2可以用这个efi吗？

### ISSUE THREAD

**Issue by cnoocyy** [hjmmc/Honor-Magicbook#21]
如题，我安装了黑果小兵的10.15.2镜像，但是驱动什么的不会弄，可以用这个efi替换吗？

**Comment by petexia** [comment]
直接在diskgenius把EFI替换就好

**Comment by cnoocyy** [comment]
> 直接在diskgenius把EFI替换就好
替换过了，进黑果直接卡黑屏

**Comment by hjmmc** [comment]
现在我用的系统就是15.2，你应该把错误信息贴上来

**Comment by cnoocyy** [comment]
> 现在我用的系统就是15.2，你应该把错误信息贴上来

真不好意思，我刚接触黑苹果不久，替换了efi后，进度条走到一半的时候就黑屏关机了，系统进不去怎么贴错误信息啊……

**Comment by cnoocyy** [comment]
> 现在我用的系统就是15.2，你应该把错误信息贴上来

我的操作是：在pe下用dg打开硬盘的esp分区，替换efi下的boot和clover文件夹。win的那个文件夹我没动，然后重启，win能进去，但是黑果进度条到一半的时候直接黑屏关机了

**Comment by xianyu-ing** [comment]
> 现在我用的系统就是15.2，你应该把错误信息贴上来

作者你的EFI 的引导程序更新了吗，我用你的 EFI 安装 10.15 进入不了系统界面

**Comment by xianyu-ing** [comment]
> > 现在我用的系统就是15.2，你应该把错误信息贴上来
> 
> 我的操作是：在pe下用dg打开硬盘的esp分区，替换efi下的boot和clover文件夹。win的那个文件夹我没动，然后重启，win能进去，但是黑果进度条到一半的时候直接黑屏关机了

猜测应该是没有指定 Clover  为主要引导程序
