### ISSUE TITLE
声卡/触摸板手势/蓝牙不能正常使用

### ISSUE THREAD

**Issue by silver7843** [hjmmc/Honor-Magicbook#23]
你好，我使用的您的EFI，同款机型但是我用的comef**t的外接小帽子USB显卡没换内置显卡，
由于不太清楚是什么版本的，我10.15.2/ 10.14.6 均使用了，
但是使用之后清除缓存之后触摸板手势依然无法使用，但是触摸板是可以用的
蓝牙无法发现新设备，发现之后也无法成功连接
声卡也无法使用，是不是因为更新的版本原因导致呢？
目前下载的EFI适用于什么版本啊？

辛苦了

**Comment by hjmmc** [comment]
可以看release的版本，目前在10.15.3正常使用。
触摸板要重建缓存，sudo kextcache -i /

**Comment by silver7843** [comment]
> 可以看release的版本，目前在10.15.3正常使用。
> 触摸板要重建缓存，sudo kextcache -i /

我也不知道为什么，我直接下载的你的efi，重建缓存了没有用，15.2 14.6 都试用过
不好意思，比较菜，我把你的efi 放进去安装的时候都开不了机的 会卡死在读条界面，所以换了一个620 通用的config的，调节跟你的config差不多一样都还是不行

**Comment by xianyu-ing** [comment]
> 可以看发行的版本，目前在10.15.3正常使用。
> 触摸板要重建缓存，sudo kextcache -i /
我也是用你最新的 EFI 也是进入不了系统界面，报错如下图：

没有开启啰嗦模式
![141581947077_ pic](https://user-images.githubusercontent.com/27983861/74659179-c8ab3e00-51ce-11ea-8c23-eae4a38b1577.jpg)

啰嗦模式下
![131581946958_ pic](https://user-images.githubusercontent.com/27983861/74659087-a0234400-51ce-11ea-988d-13b29b0f45db.jpg)
