### ISSUE TITLE
蓝牙无法正常使用

### ISSUE THREAD

**Issue by jieteman** [hjmmc/Honor-Magicbook#24]
![image](https://user-images.githubusercontent.com/52092001/75623063-8546cb80-5be1-11ea-82c7-9e5ab019860e.png)楼主蓝牙能驱动但是无法搜索到设备和进行连接，该如何进行调整？

**Comment by hjmmc** [comment]
去论坛找下其它驱动吧

**Comment by jieteman** [comment]
> 去论坛找下其它驱动吧
我找了其他的驱动也修改了我的固件ID，现在能显示固件版本为C5559，但是我还是无法使用蓝牙，头大

**Comment by zyfsy0723** [comment]
从windows重启到苹果可以用蓝牙

**Comment by jieteman** [comment]
> 从windows重启到苹果可以用蓝牙

尝试过了也无效，我特意重装了windows，可惜在windows下蓝牙也无法搜到设备

**Comment by hjmmc** [comment]
> 特意重装了windows，可惜在windows下蓝牙也无法搜到

估计是你买的模块体质不行，二手的东西质量参差不齐，建议能退换最好退换下吧。之前也试过买了个接上开机就卡死的模块。

**Comment by jieteman** [comment]
> > 特意重装了windows，可惜在windows下蓝牙也无法搜到
> 
> 估计是你买的模块体质不行，二手的东西质量参差不齐，建议能退换最好退换下吧。之前也试过买了个接上开机就卡死的模块。

我去闲鱼卖了…换个1820a试试看
