### ISSUE TITLE
大佬请问我i7的用这个efi有啥影响吗，一直在用很稳定

### ISSUE THREAD

**Issue by hongligongsi** [hjmmc/Honor-Magicbook#25]
冲14.1
到14.6
到现在的15.3
一直用你的efi
但是戳莫版不好用开机用工具重建缓存就好了

**Comment by hjmmc** [comment]
这个EFI对i5还是i7没啥影响的，显卡都是620，其它都稳定说明两个版本的模具是一样的。没问题就放心用吧。触摸板是每次更新系统都要重建缓存才能用的，可以用命令重建缓存 `sudo kextcache -i /`

**Comment by hongligongsi** [comment]
这个重建缓存 sudo kextcache -i /  不行  必须用
![Xnip2020-03-04_21-49-40](https://user-images.githubusercontent.com/60691660/75951906-13c98000-5e62-11ea-91d4-7559b1fcf52f.jpg)
