### ISSUE TITLE
Matebook D

### ISSUE THREAD

**Issue by LuigiVessella** [hjmmc/Honor-Magicbook#27]
I've used this efi on Huawei matebook D(i5 8250U) and now all is working except the battery percentage..How to solve this?

**Comment by hjmmc** [comment]
try [Matebook_D_2018_Hackintosh_OpenCore](https://github.com/Zero-zer0/Matebook_D_2018_Hackintosh_OpenCore)

**Comment by LuigiVessella** [comment]
Ok, but i've your clover, which files i've to replace precisely? 
I've smcbatterymanger

**Comment by hjmmc** [comment]
May be add [SSDT-BAT1-HUAWEI.aml](https://github.com/Zero-zer0/Matebook_D_2018_Hackintosh_OpenCore/tree/master/OC/ACPI) to Clover/ACPI/patched

But if you use my clover ver, the EC0 has rename to EC. So, you need to edit the aml file. Replace EC0 to EC__
