### ISSUE TITLE
蓝牙搜索不到任何设备且无法关闭，10.15.4的系统

### ISSUE THREAD

**Issue by suavess** [hjmmc/Honor-Magicbook#29]
![image](https://user-images.githubusercontent.com/35449657/78848539-abfbeb80-7a44-11ea-973b-e76aac467e8d.png)
![image](https://user-images.githubusercontent.com/35449657/78848585-c7ff8d00-7a44-11ea-8717-93bf0ae62ac0.png)

**Comment by hjmmc** [comment]
该issue无意义，没有提供足够信息

具体蓝牙无线驱动请参考[daliansky blog](https://blog.daliansky.net/Broadcom-WiFi-BlueTooth-BCM94352z-DW1560-the%20correct-drive-posture.html)
