### ISSUE TITLE
开启hidpi相关问题

### ISSUE THREAD

**Issue by Fromnowon** [hjmmc/Honor-Magicbook#3]
版本10.4.4，
用的这个脚本：
sh -c "$(curl -fsSL https://raw.githubusercontent.com/xzhih/one-key-hidpi/master/hidpi.sh)"

出现两个严重问题：
1、睡眠唤醒后图像只出现在左上角，需要重新睡眠再唤醒；
2、若分辨率超过***x900以上，则唤醒后出现窗口刷新雪花，其实也算是花屏了；

目前要么用低于900的分辨率，要么就别开启hidpi

**Comment by hjmmc** [comment]
我也是用 one-key-hidpi，一直都是用 810 分辨率，没出现过问题
或者你试试注入 EDID，又或者用 Hackintool 开 HIDPI 试试

**Comment by hjmmc** [comment]
看到个解决方法，使用900分辨率的可以试试

http://bbs.pcbeta.com/viewthread-1761300-1-4.html
