### ISSUE TITLE
Mute button not working

### ISSUE THREAD

**Issue by IIHiradorII** [hjmmc/Honor-Magicbook#31]
Hi,

Actually when pressing the mute button the on-screen animation appears but the audio remains a the same level as before, without actually muting

Using opencore 6.1.
The plist is nearly untouched:
I've removed the Hideself function because it's deprecated and added two kext (itlwm and Bluetooth), but I can confirm that it was not working even before those upgrades.

Using Catalina 10.15.7 
Don't remember if it was working before the update, but I don't exclude that it may have been working

**Comment by hjmmc** [comment]
Yeah, the previous absence of the mute button is working.  I need to modify some parameters and then recompile the alc kext.  Maybe the next release will be fixed.

**Comment by IIHiradorII** [comment]
Thank you very much!

Is there some way to stay tuned for the next release?

**Comment by IIHiradorII** [comment]
Thank you very much!

**Comment by hjmmc** [comment]
[fixed](https://github.com/hjmmc/Honor-Magicbook/commit/b5709cc976d7a36a09fd21e75ad649cbd3f7b449)

**Comment by IIHiradorII** [comment]
Perfect, offering you a cup of Juice ;)
