### ISSUE TITLE
Big Sur booting issue

### ISSUE THREAD

**Issue by Nonta72** [hjmmc/Honor-Magicbook#38]
Hi,

I'm currently facing booting issue on Big Sur installation with your latest release.
I have a Catalina and Big Sur installed on different partitions alongside Windows 10.
I completely removed all clover leftovers so to get a clean EFI folder.
It gets stuck everytime and fans run really loud on Big Sur. Catalina keeps rebooting on panic.

Does this have anything to do with the fact that I have installed 2 macOS versions?

**Comment by hjmmc** [comment]
Now the master EFI has been updated to oc0.6.4, please try again

**Comment by Nonta72** [comment]
Thanks for your reply
It's the same issue unfortunately.
Plus, OC doesn't detect my windows drive sometimes (I have to constantly reset the NVRAM)

**Comment by Nonta72** [comment]
Update : It doesn't work even after removing the Catalina installation (just Windows 10, Big Sur and Linux).
I managed to get it working with CLOVER 5127 for now. I suspect my UEFI partition is the culprit (probably messed up). I will delete it and recreate to see if it will change anything.

New issue : Brightness keys (F1 & F2) don't change the brightness

**Comment by hjmmc** [comment]
I tried to install Catalina on other volumes and it was ok, and the brightness key also works for me.

**Comment by Nonta72** [comment]
Hi,
Maybe my laptop is different because OpenCore still won't boot. I got brightness keys working again using a kext.
Do you have the VLT-WX0 model?
And can the BIOS version be an issue? I have upgraded mine to 1.26

**Comment by hjmmc** [comment]
VLT-W50 -- MagicBook  
VLT-WX0 -- MateBookD
Maybe you need 
https://github.com/Zero-zer0/Matebook_D_2018_Hackintosh_OpenCore

**Comment by Nonta72** [comment]
> VLT-W50 -- MagicBook
> VLT-WX0 -- MateBookD
> Maybe you need
> https://github.com/Zero-zer0/Matebook_D_2018_Hackintosh_OpenCore

I'm not sure whether that is entirely accurate because I have the MagicBook and the model is VLT-WX0 in BIOS. It's also written in front "MagicBook" and "honor" on the back (upper left side).
I suspect the BIOS has something to do with this booting issue but I will try the other repository.
On the side note, both devices (MagicBook 14 2018 and MateBook D 14 2018 are really close (only the names are different, otherwise, the components are almost the same).

**Comment by hjmmc** [comment]
I have no idea, maybe you need to downgrade the bios.
