### ISSUE TITLE
【必读】目前日常使用遇到的问题

### ISSUE THREAD

**Issue by hjmmc** [hjmmc/Honor-Magicbook#4]
~~(有时) 1.开机后蓝牙无法搜索到设备，需要休眠后重新唤醒激活蓝牙~~

~~(有时) 2.有时候声音会消失，增加音量会产生破音，需要重新休眠或重新插拔耳机后恢复~~

~~(已修复) 3.盒盖休眠唤醒后屏幕无法点亮，需要重新开合一次激活屏幕。~~

~~(已修复) 4.电量循环次数信息不准确~~

~~(很少)5.扬声器声音变小消失（使用了自编译的声卡驱动ID17，同时驱动高低音喇叭，睡眠后声音消失？开合下盖子，或暂停播放 1 分钟后恢复）~~

(缺陷)6.Handoff不完美，如无法打开手机热点，应该是dw1560/dw1830的通病

~~(已修复)7.开机直接接上HDMI会黑屏(或拔出后黑屏),开机后需熄灭一次屏幕才能修复[HDMIFix](https://github.com/hjmmc/Honor-Magicbook/tree/master/HDMIFix),无需脚本,下载最新的 EFI 即可，[修复记录](https://github.com/hjmmc/Honor-Magicbook/commit/c15c171b17138e4c4055928ba6564017ca5a7b0f)~~

~~(修复)8.休眠一晚耗电10%左右（OC支持 25 的休眠模式，加入6D补丁，修复GLAN等设备唤醒，休眠耗电<1%）~~

**Comment by yangguangxiadeyun** [comment]
请问你能够连接蓝牙鼠标吗？

**Comment by hjmmc** [comment]
> 请问你能够连接蓝牙鼠标吗？

蓝牙功能都正常

**Comment by TAOTAO5** [comment]
蓝牙功能异常是10.14.5才有的吗

**Comment by TAOTAO5** [comment]
我现在10.14.2是否可以直接升级到10.14.5

**Comment by hjmmc** [comment]
> 蓝牙功能异常是10.14.5才有的吗

或许与系统无关，有可能是不同网卡体质造成的。

小版本更新一般都没问题的，只要更新 Clover 和驱动应该就可以直接更新了。

**Comment by TAOTAO5** [comment]
谢谢

**Comment by TAOTAO5** [comment]
存在显示器亮度无法记忆的情况，每次开机亮度都只有一半

**Comment by Fromnowon** [comment]
发现进程kernel_task占用cpu偏高，导致cpu温度长期处于60以上。baidu搜了一下，说是处理掉IOPlatformPluginFamily.kext，发现没啥作用
<img width="654" alt="QQ20190531-101027@2x" src="https://user-images.githubusercontent.com/2792725/58676918-929e0380-838c-11e9-8dc6-590db14e4a42.png">

**Comment by hjmmc** [comment]
![20190531165841](https://user-images.githubusercontent.com/12729036/58694416-87b39500-83c5-11e9-828e-c73d1c91e38f.jpg)

回楼上：并不存该问题，你应该到论坛求助。

另外把 BrcmPatchRAM2.kext 和 BrcmFirmwareData.kext 放到 S/L/E 下，蓝牙失效问题暂未出现。

**Comment by Fromnowon** [comment]
感谢大佬解答，我再研究一下

**Comment by Fromnowon** [comment]
合盖子唤醒后分辨率混乱，显示设置里也不正常，10天遇到2次了。有同样情况的朋友吗？已开启hidpi

**Comment by TAOTAO5** [comment]
> 合盖子唤醒后分辨率混乱，显示设置里也不正常，10天遇到2次了。有同样情况的朋友吗？已开启hidpi，使用1680x944

把分辨率设置成1440＊810应该就能解决

**Comment by Fromnowon** [comment]
> > 合盖子唤醒后分辨率混乱，显示设置里也不正常，10天遇到2次了。有同样情况的朋友吗？已开启hidpi，使用1680x944
> 
> 把分辨率设置成1440＊810应该就能解决

810感觉偏大了点，我注入edid再观察一段时间

**Comment by jieteman** [comment]
替换了您的EFI文件升级到10.14.15进入密码输入界面键盘无法使用是什么情况？

**Comment by Fromnowon** [comment]
大佬有在用外接显示器吗？我外接1080p，笔记本内建显示器明显掉帧，感觉变成30刷新率，外接显示器正常。由于手头只有一条hdmi线，没法对线进行测试

**Comment by hjmmc** [comment]
> 大佬有在用外接显示器吗？我外接1080p，笔记本内建显示器明显掉帧，感觉变成30刷新率，外接显示器正常。由于手头只有一条hdmi线，没法对线进行测试

现在并没有用外接显示器

**Comment by TAOTAO5** [comment]
> 大佬有在用外接显示器吗？我外接1080，笔记本内建显示器明显掉帧，感觉变成30刷新率，外接显示器正常。由于手头只有一条HDMI线，没法对线进行测试

我用的两个显示器，没有掉帧啊，都是接近60帧

**Comment by Fromnowon** [comment]
> > 大佬有在用外接显示器吗？我外接1080p，笔记本内建显示器明显掉帧，感觉变成30刷新率，外接显示器正常。由于手头只有一条hdmi线，没法对线进行测试
> 
> 现在并没有用外接显示器

现在又正常了，尴尬...估计是线的问题

**Comment by Fromnowon** [comment]
> > 大佬有在用外接显示器吗？我外接1080，笔记本内建显示器明显掉帧，感觉变成30刷新率，外接显示器正常。由于手头只有一条HDMI线，没法对线进行测试
> 
> 我用的两个显示器，没有掉帧啊，都是接近60帧

那就好，我换条线试试。今早突然正常了，一脸懵

**Comment by Fromnowon** [comment]
发现问题了，顺便也发现了个触发kernel_task飙升的操作。开机后接上hdmi线内屏确实掉帧，这时候关闭显示器再点亮就正常，用的「触发角」-「左下」-「显示器置入睡眠」，如果我用「睡眠」按钮，帧数正常了，但cpu会炸，保持在3Ghz以上，活动监视器查看进程kernel_task一直再30%浮动。盒盖子倒不会这样，看来这意思是不能手动睡眠啊，目前貌似只有我遇到这问题，只在10.14.X，已经重装过了

**Comment by hjmmc** [comment]
> 开机后接上hdmi线内屏确实掉帧，这时候关闭显示器再点亮就正常，用的「触发角」-「左下」-「显示器置入睡眠」，如果我用「睡

之前貌似也遇到过刚开机蓝牙不能用要休眠后才恢复的问题。

建议：使用 Mac 系统的正确姿势应该是不关机，不使用时盖上盖子休眠，虽然黑苹果不支持深度睡眠，但周末两天待机只需 10~20%的电量而已。
<img width="270" alt="QQ20190718-090255@2x" src="https://user-images.githubusercontent.com/12729036/61421732-ea8fca00-a93a-11e9-8c8e-ecd580e9ad0c.png">

**Comment by Fromnowon** [comment]
> > 开机后接上hdmi线内屏确实掉帧，这时候关闭显示器再点亮就正常，用的「触发角」-「左下」-「显示器置入睡眠」，如果我用「睡
> 
> 之前貌似也遇到过刚开机蓝牙不能用要休眠后才恢复的问题。
> 
> 建议：使用 Mac 系统的正确姿势应该是不关机，不使用时盖上盖子休眠，虽然黑苹果不支持深度睡眠，但周末两天待机只需 10~20%的电量而已。
> <img alt="QQ20190718-090255@2x" width="270" src="https://user-images.githubusercontent.com/12729036/61421732-ea8fca00-a93a-11e9-8c8e-ecd580e9ad0c.png">

好的，谢谢大佬解答！

**Comment by AlikWu** [comment]
你更换的无线网卡购买的是什么版本的？联想版？戴尔版？奋威版？，可否提供一个链接~谢谢！

**Comment by lhzcc** [comment]
在使用中拔掉外界显示器的hdmi线的时候出现黑屏，只能按电源强制关机。

**Comment by lhzcc** [comment]
> 在使用中拔掉外界显示器的hdmi线的时候出现黑屏，只能按电源强制关机。
系统版本10.14.2

**Comment by hjmmc** [comment]
> > 在使用中拔掉外界显示器的hdmi线的时候出现黑屏，只能按电源强制关机。
> > 系统版本10.14.2

暂时只能先休眠了

休眠后再接入显示器不会出现黑屏的情况

**Comment by hjmmc** [comment]
已经使用 hotpatch 修复盒盖休眠需再开合一次才能点亮屏幕的问题。

需要使用 Clover 重命名 _LID 为 XLID，并且添加 [SSDT-LID-Wake-After-Sleep.aml](/hjmmc/Honor-Magicbook/tree/master/EFI/CLOVER/ACPI/patched) 补丁 

详情请看 [提交记录](/hjmmc/Honor-Magicbook/commit/9ac4cbc2ca19f06c8a236f2e1a41fc068909394c)

**Comment by hjmmc** [comment]
使用麦克风后扬声器声音消失的问题已经修复了，大家用正版的AppleALC驱动就好，声卡ID为57

另外已经更新适配了10.15系统，喜欢尝鲜的可以更新了

**Comment by hjmmc** [comment]
> 使用麦克风后扬声器声音消失的问题已经修复了，大家用正版的AppleALC驱动就好，声卡ID为57
> 
> 另外已经更新适配了10.15系统，喜欢尝鲜的可以更新了

新发现个问题, 无法静音, 只能减少音量, 尝试过修改扬声器可以静音,但会出现开机破音的情况.附上两个可以静音的驱动,自行选择吧.

[AppleALC(57)只能耳机静音.zip](https://github.com/hjmmc/Honor-Magicbook/files/3721748/AppleALC.57.zip)
[AppleALC(57)都能静音但开机破音.zip](https://github.com/hjmmc/Honor-Magicbook/files/3721750/AppleALC.57.zip)

**Comment by imgol** [comment]
发现一个新问题，无法使用电脑直接打开（不用事先在手机上打开热点）手机的热点（iPad的可以），必须要 在手机上先打开热点，然后在Wi-Fi的设置中刷新到Wi-Fi列表才能连接。

**Comment by HDwoald** [comment]
你们的触摸板手势能用吗(10.15)？

**Comment by jieteman** [comment]
无法升级10.15……电脑无限重启

发自我的iPhone

**Comment by HDwoald** [comment]
> 无法升级10.15……电脑无限重启 发自我的iPhone
> […](#)
> 在 2019年11月2日，01:36，HDowald ***@***.***> 写道： ﻿ 你们的触摸板手势能用吗(10.15)？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我是直接装的10.15，并不是升级，触摸板的问题某次重启后自己就好了。

**Comment by xianyu-ing** [comment]
可以自动升级到 10.15 吗？

**Comment by yimaode** [comment]
关于kernel task持续占用的那个问题：

自己用的是dell xps 9550. 黑果. 10.14.2的系统。
之前突然遇到了差不多的问题， 我的情况是只要插着电源开机，kernel task必然占用在35%左右，且一直稳定在这个占用率。cpu的温度会从正常的35升到45， 然后稳定在45.  因此只用电池的话，电脑续航相比之前会减少一半。
此外还有个特点， 只要我开机后休眠一次再唤醒（不管有没有插电源）， kernel task会瞬间正常，然后cpu温度降低，续航回升。但是每次插着电源开机必定有高占用，且不睡眠再唤醒就不会自己消失。

重装系统，恢复很早之前的系统备份（还没有这个问题的时候的备份）， 重新给CPU上散热硅脂都没有用。
最后的解决方法是，换回win，从官方途径给电脑BIOS做了升级，此外进入bios将充电设置（dell的bios里有这个东西）把之前的“以使用电源为主”改回了“标准”（也就是默认的模式），重启之后到现在大概四五天的时间没有出现此问题。

希望有所帮助。

**Comment by xianyu-ing** [comment]
> > 无法升级10.15……电脑无限重启 发自我的iPhone
> > […](#)
> > 在 2019年11月2日，01:36，HDowald _**@**_.***> 写道： ﻿ 你们的触摸板手势能用吗(10.15)？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 我是直接装的10.15，并不是升级，触摸板的问题某次重启后自己就好了。

10.15 我的喇叭不能出声音，你还是用这个 EFI 吗？使用有无问题

**Comment by hongligongsi** [comment]
> 我现在10.14.2是否可以直接升级到10.14.5

可以的我就是这么升级的

**Comment by hjmmc** [comment]
![291583456542_ pic_hd](https://user-images.githubusercontent.com/12729036/76040075-4b7f1780-5f89-11ea-8dda-3e9a30d2f596.jpg)

为了大家交流方便建了一个QQ群，入群答案是仓库地址 `https://github.com/hjmmc/Honor-Magicbook`  ，仅作为交流使用，勿在群内交易，大家可以分享自己觉得好的软件、技巧，或是提出疑问（PS：可能没人解答就是了🤷‍♀️）

**Comment by jieteman** [comment]
复制黏贴显示答案错误…

**Comment by hjmmc** [comment]
> 复制黏贴显示答案错误…

ok,是答案太长了，改为 Magicbook了
