### ISSUE TITLE
触屏版的睡眠以后触控板和屏都不工作了

### ISSUE THREAD

**Issue by fanze0806** [hjmmc/Honor-Magicbook#40]

**Comment by hjmmc** [comment]
恕我孤陋寡闻，没听过 MagicBook2018 有触屏版。因为自己手上也是只有 MagicBook2018，并不会考虑兼容其它笔记本，同模具的可以参考一些配置，去论坛寻求帮助吧。  
关于休眠后的黑屏问题，可参考LID-FIX [https://github.com/hjmmc/Honor-Magicbook/issues/4#issuecomment-541275247](https://github.com/hjmmc/Honor-Magicbook/issues/4#issuecomment-541275247)  
善用搜索引擎，have a good day.
