### ISSUE TITLE
Black screen when youtube goes fullscreen

### ISSUE THREAD

**Issue by IIHiradorII** [hjmmc/Honor-Magicbook#47]
Sometimes, when a YouTube videeo is played via Chrome in full screen mode, everything goes black while the audio keeps going.
i haven't verified if this happens also on local videos or in other browsers.
When this happens, i have to close the screen so the pc will enter in sleep mode, after reopen everything comes back.

To try this out:
After a fresh start, check this video here at minute 21 on full screen mode 
https://www.youtube.com/watch?v=1tQ5XwvjPmA

Any suggestions?
Can you verify if the same happens to you?

**Comment by hjmmc** [comment]
I don't have this problem. you can try to upgrade your Chrome.
