### ISSUE TITLE
使用InsomniaX阻止电脑进入睡眠（彻底规避睡眠问题）

### ISSUE THREAD

**Issue by Fromnowon** [hjmmc/Honor-Magicbook#7]
方法比较激进，使用此软件阻止电脑合盖、闲置时进入睡眠，比如解决开盖子两次才能点亮屏幕的问题
但副作用也很明显，电脑怎么也不会自动睡眠，只能手动点击睡眠按钮。

![](https://user-images.githubusercontent.com/1278141/59976759-5c564b80-95fb-11e9-82ee-3fb55e2db368.png)

下载：
[insomniax_6812.dmg.zip](https://github.com/hjmmc/Honor-Magicbook/files/3329561/insomniax_6812.dmg.zip)

汉化：
安装包里的汉化文件复制到程序内的语言文件夹中
<img width="1429" alt="QQ20190626-182714@2x" src="https://user-images.githubusercontent.com/2792725/60173122-ada34c80-9840-11e9-9607-f77c62006f09.png">

**Comment by hjmmc** [comment]
盒盖不就是为了睡眠？你这是何必。
