### ISSUE TITLE
2019 新版 MagicBook 相关问题

### ISSUE THREAD

**Issue by wanghaorananda** [hjmmc/Honor-Magicbook#8]

**Comment by wanghaorananda** [comment]
感谢作者不断维护此efi，我在使用作者的efi在安装10.15时，屏幕亮度会出现忽暗忽亮的情况（亮一下暗几秒如此反复）。请问如何修改呢？
谢谢

**Comment by hjmmc** [comment]
暂时没升级 14.6

你看下显示器设置那里有没有自动亮度或原彩显示，关了这两个选项

**Comment by wanghaorananda** [comment]
好的，感谢，我电脑型号是2019款intel版。可能是其他硬件规格不一，我应该如何修改呢？有关显卡ssdt的内容是不是也要修改，对于上诉问题，我使用其他电脑远程连接是不闪的，我觉得有可能是显示器型号的问题，我应该如何修改呢？谢谢作者的回复！

**Comment by hjmmc** [comment]
你的 CPU 应该是 Whiskey Lake 构架的（i5-8265u i7-8565u），那这个 EFI 的 Config 的确不适合你

可以看看使用 Hackintool 仿冒显卡教程 [8265u试试这个例子](http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1796108&highlight=Whiskey%2BLake)

用别人 config 里面的 `Devices --> Properties --> PciRoot(0x0)/Pci(0x2,0x0) ` 节点替换自己的，或者自己用 Hackintool 生成

**Comment by pushmop** [comment]
请问下锐龙版本支持黑苹果吗？

**Comment by wanghaorananda** [comment]
> 看到有人开Pro的项目了，有同型号的可以保持关注
> 
> https://github.com/GatesYang/Magicbook-Pro-16.1-Hackintosh

好的 感谢作者
