### ISSUE TITLE
有没有大神给magicbook pro做一个efi呢？

### ISSUE THREAD

**Issue by code00000001** [hjmmc/Honor-Magicbook#9]
注意是新出的magicbook pro哦，cpu是8265u的，感激不尽！！

**Comment by Dakaria0417** [comment]
同样需要呀  大神做一个吧

**Comment by AlikWu** [comment]
> 注意是新出的magicbook pro哦，cpu是8265u的，感激不尽！！

magicbook pro 的无线网卡使用的是 Intel 9560AC，此网卡使用的是是 CNVi 协议，跟换不了黑果驱动的网卡，BIOS里面限制住了
